spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\\Users\\Naos\\Desktop\\test
